#ifndef STATE_H
#define STATE_H

#include <iostream>
#include <string>

#define FILE_PORT 2222
#define AIM_PORT 1234
enum returnType{FAILCONNECT,SUCCESSCON,FAILSEND,NORETURN,SUCCESS,WRONG_ANSWER};
enum connectType{CONNECT,SENDTEXT,LOGIN,REGISTER,PWRE,ADD,SENDFILE,LISTENING,PWRE_ASK,SERVER};
enum returnState{TRUE_REQUEST,FALSE_REQUEST};

#endif // STATE_H
